manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joric
      url-base: https://github.com/joric

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nrfmicro
      remote: joric
      revision: main

  self:
    path: config
